// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Symbol table implementation internals

#include "VTestHarness__Syms.h"
#include "VTestHarness.h"
#include "VTestHarness___024unit.h"
void VTestHarness__Syms::VTestHarness__Syms_1(VTestHarness* topp) {
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__fixer__monitor_1.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.fixer.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.system_bus_xbar", "system_bus_xbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar__monitor.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.system_bus_xbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__subsystem_sbus__system_bus_xbar__monitor_1.configure(this, name(), "TestHarness.chiptop.system.subsystem_sbus.system_bus_xbar.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__buffer_1__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.buffer_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core", "core", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__csr.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.csr", "csr", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__csr_exe_unit.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.csr_exe_unit", "csr_exe_unit", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__csr_exe_unit__ifpu.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.csr_exe_unit.ifpu", "ifpu", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline", "fp_pipeline", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fp_issue_unit", "fp_issue_unit", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fp_issue_unit.slots_0", "slots_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fp_issue_unit.slots_1", "slots_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_2.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fp_issue_unit.slots_2", "slots_2", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_3.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fp_issue_unit.slots_3", "slots_3", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_4.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fp_issue_unit.slots_4", "slots_4", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_5.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fp_issue_unit.slots_5", "slots_5", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_6.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fp_issue_unit.slots_6", "slots_6", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fp_issue_unit__slots_7.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fp_issue_unit.slots_7", "slots_7", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fpiu_unit.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fpiu_unit", "fpiu_unit", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fpiu_unit__fdivsqrt.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fpiu_unit.fdivsqrt", "fdivsqrt", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_pipeline__fregfile.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_pipeline.fregfile", "fregfile", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_rename_stage.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_rename_stage", "fp_rename_stage", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_rename_stage__freelist.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_rename_stage.freelist", "freelist", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__fp_rename_stage__maptable.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.fp_rename_stage.maptable", "maptable", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.int_issue_unit", "int_issue_unit", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.int_issue_unit.slots_0", "slots_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.int_issue_unit.slots_1", "slots_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_2.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.int_issue_unit.slots_2", "slots_2", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_3.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.int_issue_unit.slots_3", "slots_3", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_4.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.int_issue_unit.slots_4", "slots_4", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_5.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.int_issue_unit.slots_5", "slots_5", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_6.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.int_issue_unit.slots_6", "slots_6", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__int_issue_unit__slots_7.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.int_issue_unit.slots_7", "slots_7", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__iregfile.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.iregfile", "iregfile", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_issue_unit", "mem_issue_unit", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_issue_unit.slots_0", "slots_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_issue_unit.slots_1", "slots_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_2.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_issue_unit.slots_2", "slots_2", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_3.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_issue_unit.slots_3", "slots_3", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_4.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_issue_unit.slots_4", "slots_4", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_5.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_issue_unit.slots_5", "slots_5", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_6.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_issue_unit.slots_6", "slots_6", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_issue_unit__slots_7.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_issue_unit.slots_7", "slots_7", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__mem_units_0__maddrcalc.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.mem_units_0.maddrcalc", "maddrcalc", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__rename_stage.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.rename_stage", "rename_stage", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__rename_stage__freelist.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.rename_stage.freelist", "freelist", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__rename_stage__maptable.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.rename_stage.maptable", "maptable", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__core__rob.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.core.rob", "rob", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.dcache", "dcache", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.dcache.mshrs", "mshrs", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mmios_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.dcache.mshrs.mmios_0", "mmios_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_0.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.dcache.mshrs.mshrs_0", "mshrs_0", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__dcache__mshrs__mshrs_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.dcache.mshrs.mshrs_1", "mshrs_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__frontend.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.frontend", "frontend", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__frontend__bpd.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.frontend.bpd", "bpd", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__frontend__icache.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.frontend.icache", "icache", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__frontend__tlb.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.frontend.tlb", "tlb", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__lsu.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.lsu", "lsu", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__lsu__dtlb.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.lsu.dtlb", "dtlb", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__ptw.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.ptw", "ptw", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__tlMasterXbar.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.tlMasterXbar", "tlMasterXbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__tlMasterXbar__monitor.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.tlMasterXbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__tile_prci_domain__tile_reset_domain__boom_tile__tlMasterXbar__monitor_1.configure(this, name(), "TestHarness.chiptop.system.tile_prci_domain.tile_reset_domain.boom_tile.tlMasterXbar.monitor_1", "monitor_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__chiptop__system__uartClockDomainWrapper__uart_0__monitor.configure(this, name(), "TestHarness.chiptop.system.uartClockDomainWrapper.uart_0.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__adapter.configure(this, name(), "TestHarness.ram.adapter", "adapter", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__buffer_1__monitor.configure(this, name(), "TestHarness.ram.buffer_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__buffer__monitor.configure(this, name(), "TestHarness.ram.buffer.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter.configure(this, name(), "TestHarness.ram.fragmenter", "fragmenter", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter_1.configure(this, name(), "TestHarness.ram.fragmenter_1", "fragmenter_1", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter_1__monitor.configure(this, name(), "TestHarness.ram.fragmenter_1.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__fragmenter__monitor.configure(this, name(), "TestHarness.ram.fragmenter.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__rom__monitor.configure(this, name(), "TestHarness.ram.rom.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__serdesser__monitor.configure(this, name(), "TestHarness.ram.serdesser.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__srams__monitor.configure(this, name(), "TestHarness.ram.srams.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__xbar.configure(this, name(), "TestHarness.ram.xbar", "xbar", -9, VerilatedScope::SCOPE_OTHER);
    __Vscope_TestHarness__ram__xbar__monitor.configure(this, name(), "TestHarness.ram.xbar.monitor", "monitor", -9, VerilatedScope::SCOPE_OTHER);
    
    // Setup scope hierarchy
    
}
